export enum workActionTypes {
  GET_WORK_SUCCESS = 'GET_WORK_SUCCESS',
  OPEN_DISPUTE_SUCCESS = 'OPEN_DISPUTE_SUCCESS',
  OPEN_DISPUTE_FAILURE = 'OPEN_DISPUTE_FAILURE',
  ADD_DISPUTE_SUCCESS = 'ADD_DISPUTE_SUCCESS',
  REFUSE_DISPUTE_SUCCESS = 'REFUSE_DISPUTE_SUCCESS',
  ADD_DISPUTE_MEDIATOR = 'ADD_DISPUTE_MEDIATOR',
  CLOSE_DISPUTE = 'CLOSE_DISPUTE',
  CLEAR_NEW_DISPUTE = 'CLEAR_NEW_DISPUTE',
}
