export enum authActionTypes {
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  AUTH_ERROR = 'AUTH_ERROR',
  CLEAR_ERROR = 'CLEAR_ERROR',
  REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS',
}
