export const appRouters = {
  about: '/about',
  account: '/account',
  administrative: '/categories/administrative',
  allCategories: '/categories/all-categories',
  arbitration: '/categories/arbitration',
  blog: '/blog',
  civil: '/categories/civil',
  confirm_code: '/confirm-code',
  error: '/error',
  family: '/categories/family',
  forgot_password: '/forgot-password',
  home: '/',
  information: '/information',
  login: '/login',
  newDispute: '/work/new-dispute',
  partners: '/partners',
  privacyPolicy: '/privacy-policy',
  registration: '/registration',
  userAgreement: '/user-agreement',
  work: '/work',
};
